# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#run
run:
  prefix: "cutouts_det_capexp_"
  name: prova
  scenarios:
    enable: false
    file: config/cutouts_prices_uncertainty/scenarios_cutouts_det_capexp.yaml
  disable_progressbar: false
  shared_resources:
    policy: false
    exclude: []
  use_shadow_directory: false

snapshots:
  start: "2000-01-01"
  end: "2001-01-01"
  inclusive: left

  # docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#atlite
atlite:
  default_cutout: "europe-2000-era5"
  nprocesses: 16
  show_progress: true
  cutouts:
    "europe-2000-era5":
      module: era5
      x:
      - -12.0
      - 42.0
      'y':
      - 33.0
      - 72.0
      dx: 0.3
      dy: 0.3
      time:
      - '2000'
      - '2000'
      chunks:
        time: 500
      prepare_kwargs:
        features: []
        monthly_requests: true
        tmpdir: ./cutouts_tmp/

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#load
load:
  fill_gaps:
    enable: true
    interpolate_limit: 6
    time_shift_for_large_gaps: 1w
  manual_adjustments: true
  scaling_factor: 1.0
  fixed_year: 2013
  supplement_synthetic: true
  distribution_key:
    gdp: 0.6
    population: 0.4

solving:
  load_shedding: true